name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: uday2ml/my-image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s#image: .*#image: ${{ env.IMAGE_NAME }}:${{ github.run_number }}#g" Deployments/deployment.yml

      - name: Commit updated deployment.yml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Deployments/deployment.yml
          git commit -m "Update image tag to ${{ github.run_number }}" || echo "No changes to commit"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
